### ISSUE TITLE
[功能需求]为日间和黑夜模式分别设置不同的logo链接

### ISSUE THREAD

**Issue by Palentum** [sakurauius/SKY_Theme#10]
支持为日间和黑夜模式分别设置不同的logo链接

以下图为演示站
![屏幕截图 2023-11-25 060534](https://github.com/sakurauius/SKY_Theme/assets/79781425/55171169-e0bf-4fc1-9e33-22a89c8b4e40)
![屏幕截图 2023-11-25 060539](https://github.com/sakurauius/SKY_Theme/assets/79781425/201b3da3-94f9-468f-ac5c-fb7d4286eb96)

**Comment by sakurauius** [comment]
这个功能有，自行修改app.php即可
