### ISSUE TITLE
[BUG]用户中心侧边栏收起时显示的图片长宽设定错误

### ISSUE THREAD

**Issue by Palentum** [sakurauius/SKY_Theme#11]
**描述错误**
用户中心侧边栏收起时显示的图片长宽设定错误，错误地通用了展开时显示的LOGO图片的长宽，导致收起时显示的LOGO图片被拉伸显示不正常

**复现**
100%复现

**预期行为**
能按正常比例显示图片，可以给收起时的logo图片也单独加个长宽设置项

**截图**
![image](https://github.com/sakurauius/SKY_Theme/assets/79781425/95c20796-7d0d-4056-a58f-33ca94b9b9ee)

**Comment by sakurauius** [comment]
1.2.0更新
