### ISSUE TITLE
[BUG]续费不支持月付订阅时报错

### ISSUE THREAD

**Issue by Mintapril** [sakurauius/SKY_Theme#27]
**描述错误**
用户尝试续费不支持月付的订阅时页面会报错，但不影响续费

**复制**
重现该行为的步骤：
1. 转到“控制台”
2. 单击页面上方的“续费订阅”
4. 在“订阅费用”字样下面可以看到错误

**预期行为**
无报错，一切正常显示

**截图**
![IMG_8595](https://github.com/sakurauius/SKY_Theme/assets/37259198/2638ba9f-a517-4b73-9557-4ec1a9f66d17)

**Comment by sakurauius** [comment]
试了下，无法复现，可能是你分支的问题
