### ISSUE TITLE
[功能需求]希望兼容AppleAutoPro

### ISSUE THREAD

**Issue by jieinfo** [sakurauius/SKY_Theme#29]
知名的apple id解锁项目
这是项目地址https://docs.appleidauto.org

**Comment by longyi8** [comment]
![image](https://github.com/sakurauius/SKY_Theme/assets/68991513/2b20e242-5297-416c-b054-021f87b1c95b)
经过测试，我想它在早期版本就已经兼容了，您只需要按照此项目的文档修改即可
