### ISSUE TITLE
[BUG]用户中心侧边栏收起时显示的LOGO长宽比例渲染错误

### ISSUE THREAD

**Issue by Palentum** [sakurauius/SKY_Theme#31]
**描述错误**
用户中心侧边栏收起时显示的LOGO长宽比例渲染错误

**截图**
![2023-12-20 022134](https://github.com/sakurauius/SKY_Theme/assets/79781425/6f1346f2-e7b3-4d3b-b51e-39b9994b7b63)

**Comment by sakurauius** [comment]
已修复
