### ISSUE TITLE
[BUG] \app\module\multi-language\language\user\zh-cn.php 第170行错字

### ISSUE THREAD

**Issue by Palentum** [sakurauius/SKY_Theme#32]
**描述错误**
\app\module\multi-language\language\user\zh-cn.php 第170行错字，已失效 打成 以失效

**截图**
![image](https://github.com/sakurauius/SKY_Theme/assets/79781425/8ebd1f1f-cb3d-42bc-9cec-53e6d6aa5d77)

**Comment by sakurauius** [comment]
已修改
