### ISSUE TITLE
[BUG]找回密码界面，点击提交按钮后的提示语容易产生误导

### ISSUE THREAD

**Issue by kintouns** [sakurauius/SKY_Theme#44]
**描述错误**
密码重置页面，最后一步点击提交按钮后出现的提示语容易误导用户，以为哪个步骤出错了，如下图所示

**预期行为**
希望可以修改一下提交后的提示语，最好是明确告知用户，密码已经重置成功

**截图**
![截图](https://github.com/sakurauius/SKY_Theme/assets/149152946/e3c9c84e-d667-4cb4-8a54-2a90b987cb6f)

**Comment by sakurauidev** [comment]
已修复
