### ISSUE TITLE
[BUG]app.php和theme.php都设置了TG群的信息和开关，但是个人中心TG群不显示，点击加入群组也无效

### ISSUE THREAD

**Issue by ppjack-code** [sakurauius/SKY_Theme#46]
**描述错误**
app.php和theme.php都设置了TG群的信息和开关，但是个人中心TG群不显示，点击加入群组也无效

![image](https://github.com/sakurauius/SKY_Theme/assets/22497103/ad7ace51-8922-4c5b-b586-79afb6138959)

**Comment by sakurauidev** [comment]
完成
