### ISSUE TITLE
[功能需求]增加前端邮箱限制

### ISSUE THREAD

**Issue by yishenbaiyi** [sakurauius/SKY_Theme#5]
由于v2b之前是通过前端限制实现的，API并没有进行验证，这导致尽管后台已设置了邮箱限制，但当前主题前端却未进行相应限制，使得仍然可以成功注册。希望在当前主题的前端注册过程中能够新增一个邮箱选择的下拉框。

**Comment by sakurauius** [comment]
1.1.4更新
