### ISSUE TITLE
[功能需求]优化使用文档打开方式

### ISSUE THREAD

**Issue by longyi8** [sakurauius/SKY_Theme#6]
目前状态：打开使用文档界面后，需要点击“阅读”才能打开指定的文档，但是字体过于小，会引起客户不必要的麻烦

希望状态：将不只限于“阅读”，点击某一文档的区块后，可以直接打开这个文档。或是在右边增加一个“阅读文档”的大按钮。

理想状态：用户打开使用文档后，点击想要查看文档的区块可以直接打开，或是有显著的阅读按钮

![image](https://github.com/sakurauius/SKY_Theme/assets/68991513/45a27680-4405-47b8-8cc5-949e72cbbace)

**Comment by sakurauidev** [comment]
完成
